import Head from "next/head";
import Navbar from "../components/Navbar";
import PricesSection from "../components/PricesSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <div className="w-full hero bg-dark min-h-screen">
          <div className="bg-dark text-color mt-24 px-3 max-w-6xl relative z-20 mx-auto ">
            <h1 className="text-8xl font-bold leading-[108px] py-8 ">
              Results focused design & development agency.
            </h1>
            <p className="text-lg py-4 max-w-[640px] font-semibold">
              Extend your team with our high performing specialists or hire us
              to shape your product from scratch. Either way, we’ll get your
              product off the ground and build a momentum for your success.
            </p>
          </div>
        </div>
        <div>
          <PricesSection
            img={"/assets/computer.png"}
            tags={["product design", "quality assurance"]}
            title="Corrily: Optimize prices
                to maximize revenue"
            paragraph="Corrily tailors your prices and discounts
             to the needs of different user segments in order to increase 
             your revenue. Cinnamon was tasked with creating a new visual identity 
             for Corrily and incorporating a fresh, and stunning website redesign."
          ></PricesSection>
        </div>
      </main>
    </div>
  );
}
