import Head from "next/head";
import Navbar from "../components/layouts/Navbar";
import PricesSection from "../components/sections/PricesSection";
import HeroSection from "./../components/sections/HeroSection";
import ServiceSection from "../components/sections/services/ServiceSection";
import TeamSection from "../components/sections/TeamSection";
import CaseStudy from "../components/sections/CaseStudy";
import AboutUs from "../components/sections/AboutUs";
import CollegeSection from "../components/sections/CollegeSection";
import DeveloperTeam from "../components/sections/DeveloperTeam";
import OfficesSection from "../components/sections/offices/OfficesSection";
import BlogsSection from "../components/sections/blogs/BlogsSection";
import ContactUs from "../components/sections/ContactUs";
import Footer from "../components/layouts/Footer";

export default function Home() {
  let cards = [
    {
      className: "bg-apple",
      img: "/assets/computer.png",
      tags: ["product design", "quality assurance"],
      title: (
        <>
          Corrily: Optimize prices
          <br />
          to maximize revenue
        </>
      ),
      paragraph:
        "Corrily tailors your prices and discounts to the needs of different user segments in order to increase your revenue. Cinnamon was tasked with creating a new visual identity for Corrily and incorporating a fresh, and stunning website redesign.",
    },
    {
      className: "bg-purple",
      img: "/assets/computer.png",
      tags: ["product design", "web development"],
      title: (
        <>
          Fiona: Engage &
          <br />
          Decide
        </>
      ),
      paragraph:
        "Fiona is a fintech consumer-facing website that enables users to search for financial products, discover them, and receive personalized recommendations.",
    },
    {
      className: "bg-yellow",
      img: "/assets/tablets.png",
      tags: ["product design", "web development", "quality assurance"],
      title: (
        <>
          Ukulele:
          <br />
          The largest ukulele tabs archive
        </>
      ),

      paragraph:
        "Ukulele is the number one ukulele community, where players of any level can find the most complete tabs and chords. Cinnamon offered a complete platform redesign including expansions and new features, focusing on keeping the user longer on the website.",
    },
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <HeroSection />
        <div>
          {cards.map((card) =>  (
              <PricesSection
                className={card.className}
                img={card.img}
                tags={card.tags}
                title={card.title}
                paragraph={card.paragraph}
              />
            ))}
        </div>
        <ServiceSection />
        <TeamSection />
        <CaseStudy />
        <AboutUs />
        <CollegeSection />
        <DeveloperTeam />
        <OfficesSection />
        <BlogsSection />
        <ContactUs />
        <Footer />
      </main>
    </div>
  );
}
